# Generated by Django 4.1 on 2022-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(max_length=64),
        ),
    ]
