# Generated by Django 4.1 on 2022-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_course_name_alter_course_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(),
        ),
    ]
